### ISSUE TITLE
CMake: add_subdirectory given source "googletest" which is not an existing   directory

### ISSUE THREAD

**Issue by Ryanf55** [dronecan/libcanard#28]
https://github.com/dronecan/libcanard/blob/5efa0a4ea20542f330d93a3197cc8d34c29ea2c1/CMakeLists.txt#L38

In the CMakeLists, it's not building because googletest directory doesn't exist.  

Host OS: Ubuntu 22.04
CMake version: 3.22.1

Steps to reproduce:
1. Clone
2. `cd libcanard`
3. `cmake -S . -B build`

I'd recommend using something along the lines of these:
https://cmake.org/cmake/help/latest/module/FindGTest.html
https://cmake.org/cmake/help/latest/module/GoogleTest.html

We are having to make workaround for this here:
https://github.com/ArduPilot/ardupilot/pull/23574

Based on the design goals of the library, it says it's supposed to be portable. Considering many developers develop on Ubuntu 22.04, and cmake is the most common build system, it seems like this should be enforced to work in CI rather than making calls directly to g++ IMHO.

**Comment by tridge** [comment]
fixed by #31
