### ISSUE TITLE
Cherry pick commit from uavcan repo

### ISSUE THREAD

**Issue by a1ien** [dronecan/libcanard#6]
I think it's necessary Cherry pick this commits from uavcan repo https://github.com/UAVCAN/libcanard/pull/190

**Comment by adolfogc** [comment]
Hi @a1ien, I adapted your fix and submitted a PR, can you kindly review it? Thank you in advance.

**Comment by adolfogc** [comment]
PR is #19

**Comment by tridge** [comment]
fixed, thanks
